theme = "gruvbox_dark_hard_fixed"

[editor]
line-number = "relative"
bufferline = "always"
mouse = false
completion-trigger-len = 1 
idle-timeout = 0
color-modes = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
C-c = ["collapse_selection", "keep_primary_selection"]
# substitute line w/ indenting
A-x = ["extend_line_below", "trim_selections", "delete_selection", "open_above"] 
"A-K" = "no_op"

[keys.normal."space"]
c = "toggle_comments"
C = ":buffer-close"

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"
