theme = "gruvbox_dark_hard_fixed"

[editor]
line-number = "relative"
bufferline = "always"
# mouse = false
completion-trigger-len = 1 
idle-timeout = 0
color-modes = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[keys.normal]
# Line up
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# Line down
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

C-c = ["collapse_selection", "keep_primary_selection"]
# A-x = ["extend_line_below", "trim_selections", "delete_selection", "open_above"] 
"A-K" = "no_op"

[keys.normal."space"]
Q = ":quit-all!"
W = [":format", ":write"]
F = ":format"
c = "toggle_comments"
C = ":buffer-close"

[keys.insert]
C-c = "normal_mode"
# For xkde terminal
C-h = "delete_char_forward"

[keys.select]
# Ctrl+C Exit
C-c = "normal_mode"

C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]