theme = "gruvbox"

[editor]
line-number = "relative"
bufferline = "multiple"

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"

[keys.normal]
C-c = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"