theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
bufferline = "always"
mouse = false
completion-trigger-len = 1 
idle-timeout = 0
auto-save = true

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.soft-wrap]
enable = true

[keys.insert]
C-c = "normal_mode"

[keys.select]
C-c = "normal_mode"

[keys.normal]
C-c = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
c = "toggle_comments"

[editor.cursor-shape]
insert = "bar"